joomla_v4/translations/core/installation/language/es-ES/joomla.ini, joomla_v4/translations/core/installation/language/es-ES/langmetadata.xml
Installation es-ES language files for Joomla 4
=> Add installation es-ES language files

Configurations/Crowdin-J4-Installer.yml
Remove the following xml files from translation:
- version
- creationDate
- author
- copyright
- license
=> Lockdown installation metadata for installation

.github/workflows/local-upload-liechtenstein.yml, .github/workflows/local-upload-luxembourg.yml, .github/workflows/local-upload-swiss.yml
and pronunciation for LI and LU upload config
=> Add swiss upload config

.github/workflows/core-get-language-source-v4.yml, Configurations/Crowdin-J4-All.yml, Configurations/Crowdin-J4-Installer.yml
In 1.4.7 CLI was updated and it's more sensitive to the base_path.
=> fix base_path

Configurations/Crowdin-J4-All.yml
this workaround must resolve error in "J4 Get Core Source Language files"
=> workaround for github action

joomla_v4/translations/core/installation/language/ru-RU/joomla.ini, joomla_v4/translations/core/installation/language/ru-RU/langmetadata.xml
Hi! Russian language for installation folder.
=> Russian language for installation folder

joomla_v4/translations/core/installation/language/ru-RU/joomla.ini, joomla_v4/translations/core/installation/language/ru-RU/langmetadata.xml
The actual file will finally get into the Joomla main branch. I noticed that the copyrights were changed and the version was downgraded in PR https://github.com/joomla/joomla-cms/pull/37835. Fixing...
=> Fix copyrights for ru-RU

.github/workflows/_en-gb-localise.yml
- Adds a comment to PR if triggered from a PR
- Replaces a PR comment content if comment already exists
- Can be triggered manually - in that case output is available in details of the workflow run for now
fix https://github.com/joomla/core-translations/issues/378
=> [GHA] Check if En_GBLocalise class exist in translations

.github/workflows/_en-gb-localise.yml, .github/workflows/_pr-comment.yml
After merge Pr comments should work also from forks. for now comment is added or edited only on failure.
=> Add PR comment for _en-gb-localise.yml workflow

.github/workflows/_en-gb-localise.yml, .github/workflows/_pr-comment.yml
Workflows are updated to add change small changes in appearance of the comment - see https://github.com/wojsmol/core-translations/pull/3#issuecomment-1222184248
Additionally I used [marocchino/on_artifact ](https://github.com/marocchino/on_artifact) action to download artefact generated in _en-gb-localise.yml in the Pr comment workflow.
=> Update _en-gb-localise.yml and _pr-comment.yml workflows

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml
Try to run tests on crowdin PR'a and eliminate need  of closing and reopening of normal PR to get tests results.
=> Try to run tests on crowdin PR creation

.github/workflows/_pr-comment.yml
Add issue write permission for pr comment workflow.
=> Add write permission for pr comment workflow

.github/workflows/_pr-comment.yml
Add permission in PR comment workflow
=> Add download artifact permission to PR comment workflow

.github/workflows/_jexec_translations.yml, .github/workflows/_pr-comment_jexec.yml
As disused on Glip with @tecpromotion here are workflows to check if php files in translations are contenting `JEXEC`.
=> Add JEXEC check workflows and update to en-gb-localise check

.github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml, .github/workflows/_pr-comment_jexec.yml
Fix for the PR number fallback and JEXEC log display in comment.
=> Fix PR number falback and JEXEC log display

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
Try to restore checks statuses in crowdin PR's by using https://github.com/haya14busa/action-workflow_run-status
=> Try to restore check status to PR

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
Update workflows permissions to fix failures.
=> Update workflows permissions

.github/workflows/local-upload-polish.yml
remove leading `/` from path to fix the workflow
=> remove leading / feom path

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
Temporally remove permissions limitations.
=> Temporally remove permissions limitations

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
This PR:
- adds tests statuses to crowdin PR's
- restores permissions
- create comment only on a test failure
=> Add tests statuses to crowdin PR's

.github/dependabot.yml
Documentation of dependabot configuration file https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
This also requires enabling of Dependabot Alerts and Dependency Graph in repo settings.
=> Add basic dependabot configuration

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
In this attempt I'm using https://github.com/marketplace/actions/pull-request-comment-branch to get PR metadata and https://github.com/marketplace/actions/set-commit-status to set statuses.
=> Add statuses in crowdin pull requests

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
fix workflow permission after https://github.com/joomla/core-translations/pull/436
=> fix workflows permissions

joomla_v4/translations/package/pl-PL/administrator/language/pl-PL/com_config.ini, joomla_v4/translations/package/pl-PL/administrator/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/administrator/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/api/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/api/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/pkg_pl-PL.xml
This is a small bugfix release.
cc @zwiastunsw
=> Update Polish translation to v4.2.2.2

.github/workflows/_check-php-code.yml, .github/workflows/_en-gb-localise.yml, .github/workflows/_jexec_translations.yml
This PR adds push trigger to test workflows for crowdin PR's
=> Add push trigger for crowdin PR's

.github/workflows/crowdin-v4-dl-package-translations.yml
Authenticate as Translation Bot in crowdin PR's commits other then first commit.
https://github.com/crowdin/github-action/blob/bfdb7f723158f15da1d1c44ca7cbc014ddd60ff3/entrypoint.sh#L136-L169
=> Authenticate as Translation Bot

.github/workflows/_pr-comment.yml, .github/workflows/_pr-comment_jexec.yml
As there is no stable release with fixes for nodejs 16
=> Temporally use `marocchino/on_artifact@main`

.github/workflows/local-upload-polish.yml
additional code has been removed again.
fyi @wojsmol 
@tecpromotion keeps an eye on the uploads and reacts promptly.
=> reset polish upload action

joomla_v4/translations/package/pl-PL/administrator/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/administrator/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/api/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/api/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/language/pl-PL/install.xml, joomla_v4/translations/package/pl-PL/language/pl-PL/langmetadata.xml, joomla_v4/translations/package/pl-PL/pkg_pl-PL.xml
This release fixes small issues with package versioning.
=> Update polish translation to version 4.2.8.2

.github/workflows/core-get-language-source-v4.yml
=> change default branch to 4.3.-dev

.github/workflows/crowdin-v3-buildproject.yml, .github/workflows/crowdin-v4-buildproject.yml, Configurations/Crowdin-J4-All.yml, Configurations/Crowdin-J4-Installer.yml, Configurations/Crowdin-J5-All.yml, Configurations/Crowdin-J5-Installer.yml, README.md
=> update to secrets.CROWDIN_PROJECT_ID

.github/workflows/core-get-language-source-v4.yml, Configurations/Crowdin-J4-All.yml, Configurations/Crowdin-J4-Installer.yml, Configurations/Crowdin-J5-All.yml, Configurations/Crowdin-J5-Installer.yml
=> fix project_id_env

.github/workflows/remote-get-japanese.yml, .github/workflows/remote-get-russian.yml, .github/workflows/remote-get-spanish.yml, .github/workflows/remote-get-ukrainian.yml
actions of remote get fails since Jul 2, 2023
=> add project id to env (remote get)

.github/workflows/core-get-language-source-v4.yml
Preparation for the branch change from 4.3-dev to 4.4-dev
=> 4.3-dev to 4.4-dev

.github/workflows/_en-gb-localise-v4.yml, .github/workflows/_en-gb-localise-v5.yml, .github/workflows/_jexec_translations-v4.yml, .github/workflows/_jexec_translations-v5.yml, .github/workflows/_long-arrays-localise-v4.yml, .github/workflows/_long-arrays-localise-v5.yml, .github/workflows/_pr-commen_long_arrays.yml, .github/workflows/_pr-comment.yml, .github/workflows/_pr-comment_jexec.yml
Because for strange reason step level ifs are not working.
=> Separate v4 and v5 checks

.github/workflows/crowdin-v4-dl-package-translations.yml, .github/workflows/crowdin-v5-dl-package-translations.yml
Test fix implemented in crowdin github action https://github.com/crowdin/github-action/issues/142#issuecomment-1761145342
=> Try to run test on every ccrowdin commit instead just the first one

.github/workflows/crowdin-v4-dl-package-translations.yml, .github/workflows/crowdin-v5-dl-package-translations.yml
Try to run tests on all commits of crowdin PR's - see https://github.com/crowdin/github-action/issues/142#issuecomment-1768249241
=> Try to run tests on all commits

.github/workflows/crowdin-v4-dl-package-translations.yml, .github/workflows/crowdin-v5-dl-package-translations.yml
Use Translations Bot  token in checkout instead of standard github token.
=> use token in checkout

.github/workflows/core-get-language-source-v5.yml
Please do not merge before 19 March 2025.
=> change to 5.3-dev branch

.github/CODEOWNERS, .github/dependabot.yml
fixing reviewers configuration in the repository:
- fix CODEOWNERS - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
- removing reviewers from dependabot configuration https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
=> Fix reviewers

.github/workflows/_en-gb-localise-v6.yml, .github/workflows/_jexec_translations-v6.yml, .github/workflows/_long-arrays-localise-v6.yml, .github/workflows/crowdin-v6-buildproject.yml, .github/workflows/crowdin-v6-dl-installer-translations.yml, .github/workflows/crowdin-v6-dl-package-translations.yml, README.md
=> Add GHA for Joomla 6
